---
- name: Ensure directory exists
  file:
    path: /opt/node-{{ version }}
    state: directory
    mode: 0755

- name: Download archive
  unarchive: # noqa 208
    src: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-linux-x64.tar.gz
    dest: /opt/node-{{ version }}
    extra_opts:
      - --strip-components=1
    remote_src: true
  when: ansible_architecture == 'x86_64'
