---
- name: Configure HTTP VHost
  import_role:
    name: nginx
  vars:
    sites: '{{ [ { "key": site ~ "-http", "value": lookup("template", "http.conf.j2") } ] | items2dict }}'

- name: Ensure NGinx config is reloaded
  meta: flush_handlers

- name: Create password file
  include_role:
    name: htpasswd
  vars:
    htpasswd_path: /etc/nginx/{{ site }}.htpasswd
    htpasswd_user: '{{ basic_auth_user | default(site) }}'
    htpasswd_password: '{{ basic_auth_password }}'
  when: basic_auth_password is defined and basic_auth_password is not none

- name: Generate certificates
  import_role:
    name: letsencrypt
  vars:
    deploy_hook: service nginx reload
    certificates:
      - domain: '{{ domain }}'
        webroot: '{{ webroot }}'

- name: Configure HTTPS VHost
  include_role:
    name: nginx
  vars:
    sites: '{{ [ { "key": site ~ "-https", "value": lookup("template", "https.conf.j2") } ] | items2dict }}'
