---
- import_role:
    name: nginx
  vars:
    sites:
      '{{ site }}-http': '{{ lookup("template", "http.conf.j2") }}'

- meta: flush_handlers

- import_role:
    name: letsencrypt
  vars:
    deploy_hook: service nginx reload
    certificates:
      - domain: '{{ domain }}'
        webroot: /var/www/html/

- include_role:
    name: nginx
  vars:
    sites:
      '{{ site }}-https': '{{ lookup("template", "https.conf.j2") }}'
