version: 2.1

jobs:
  lint-ansible:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - run:
          name: Install ansible-lint
          command: sudo pip install ansible-lint==4.3.5
      - checkout
      - run:
          name: Run ansible-lint
          command: ansible-lint */

workflows:
  version: 2

  build:
    jobs:
      - lint-ansible
