---
- name: Find the artifact URL
  uri:
    url: https://circleci.com/api/v1.1/project/github/{{ repository_name }}/{{ last_build.build_num }}/artifacts
    headers:
       accept: application/json
       Circle-Token: '{{ circleci_token }}'
  register: artifacts

- name: Register artifact_url variable
  set_fact:
    artifact_url: '{{ artifacts.json|json_query(query) }}'
  vars:
    query: '[?path==`{{ (artifact_path is defined) | ternary(artifact_path, "home/circleci/project/" ~ artifact|default("")) }}`].url | [0]'

- name: Check that the artifact was found
  fail:
    msg: 'Specified artifact could not be found: {{ artifact }}'
  when: (artifact_url | length) == 0

- name: Initialize the deploy
  deploy_helper:
    path: '{{ path }}'

- name: Create release directory
  file:
    path: '{{ deploy_helper.new_release_path }}'
    state: directory
    mode: 0755

- name: Add an unfinished file
  file:
    path: '{{ deploy_helper.new_release_path }}/{{ deploy_helper.unfinished_filename }}'
    state: touch
    mode: 0644

- name: Download the archive
  get_url:
    url: '{{ artifact_url }}'
    dest: '{{ deploy_helper.new_release_path }}/archive.tar.gz'
    headers:
      Circle-Token: '{{ circleci_token }}'

- name: Extract the archive
  unarchive: # noqa 208
    remote_src: true
    src: '{{ deploy_helper.new_release_path }}/archive.tar.gz'
    dest: '{{ deploy_helper.new_release_path }}'

- name: Remove the archive
  file:
    path: '{{ deploy_helper.new_release_path }}/archive.tar.gz'
    state: absent

- name: Create the shared paths if they do not exist
  file:
    path: '{{ deploy_helper.shared_path }}/{{ item }}'
    state: directory
  with_items: '{{ shared_paths }}'

- name: Setup shared paths rights
  file:
    path: '{{ deploy_helper.shared_path }}/{{ item }}'
    state: directory
    owner: '{{ app_user }}'
    recurse: true
    follow: true
  with_items: '{{ shared_paths }}'

- name: Link the shared paths
  file:
    path: '{{ deploy_helper.new_release_path }}/{{ item }}'
    state: link
    src: '{{ deploy_helper.shared_path }}/{{ item }}'
  with_items: '{{ shared_paths }}'

- name: Setup rights
  file:
    path: '{{ deploy_helper.new_release_path }}/{{ item }}'
    state: directory
    owner: '{{ app_user }}'
    recurse: true
    follow: false
  with_items: '{{ writable_paths }}'

- name: Run before_finalize commands
  command: '{{ item }}' # noqa 301
  args:
    chdir: '{{ deploy_helper.new_release_path }}'
  with_items: '{{ before_finalize|default([]) }}'

- name: Finalize the deploy
  deploy_helper:
    path: '{{ deploy_helper.project_path }}'
    release: '{{ deploy_helper.new_release }}'
    state: finalize

- name: Run after_finalize commands
  command: '{{ item }}' # noqa 301
  args:
    chdir: '{{ deploy_helper.new_release_path }}'
  with_items: '{{ after_finalize|default([]) }}'
