name: ansible-lint

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ansible/ansible-lint-action@v6.11.0
